name: 构建并发布 Docker 镜像

on:
  workflow_dispatch: # 添加手动触发事件
#   push:
#     branches:
#       - main # 监听 main 分支的推送事件
#     paths-ignore:
#       - 'README.md' # 忽略 README.md 的更改
#       - '.github/workflows/docker-publish.yml' # 忽略此工作流文件的更改
#       - 'readme.txt'
#       - '.gitignore'
#   pull_request:
#     branches:
#       - main
#     paths-ignore:
#       - 'README.md' # 忽略 README.md 的更改
#       - '.github/workflows/docker-publish.yml' # 忽略此工作流文件的更改
#       - 'readme.txt'
#       - '.gitignore'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 QEMU 以支持多架构构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 构建并推送多架构镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64 # 支持的架构
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cloud-channel-py:latest
